name: Build Actions

on:
  push:
    branches:
      - main

jobs:
  action-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Action
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          npm ci
          npm run build
          git config --local user.email "lee-ww@naver.com"
          git config --local user.name "Isaac Lee"
          git status
          git add .
          git commit -m 'Build automation'
          git push origin ${BRANCH_NAME}
        shell: bash
